#!/usr/bin/env python3
# Generate complete English study book from research file - self-sufficient for 90+ percentile

# Read research file if exists
research_path = "ENGLISH_FINAL_90PLUS_PAPER_FIGHT_NOTES.txt"
research_content = ""
try:
    with open(research_path, 'r', encoding='utf-8') as rf:
        research_content = rf.read()
except:
    research_content = "Research file not found, using blueprint"

# Build complete study book markdown
md = []

md.append("# AGNIVEER VAYU GROUP XY — COMPLETE ENGLISH STUDY BOOK — 90+ PERCENTILE — SELF-SUFFICIENT EXAM-FIGHTING SYSTEM")
md.append("")
md.append("> Based on deep analysis of 7 papers, ~147 English PYQs, 6 passages, 120+ independent mechanisms. [OBSERVED] All claims verified against PYQs. No false guarantee. Honest ROI.")
md.append("")
md.append("## RESEARCH FOUNDATION PRESERVED")
md.append("- Dataset: 7 papers, 16 Nov 2024 to 30 Mar 2026 Official Shift1, ~147 English Qs")
md.append("- Independent Mechanisms: ~120-130")
md.append("- Exact repeats: 0 exact same English Q across papers [OBSERVED], Template repeats 10+ (passive voice wording)")
md.append("- Near repeats: ~15 clusters (Each have, Since five years, Absolutely best, Deals in, Discussion about, Humayun built, I can fix tomorrow, vacuum grateful)")
md.append("- Confidence: HIGH for Grammar Error, Preposition Article, Voice Speech, Spelling. MEDIUM for Synonym Antonym One Word Rearrangement Comprehension. LOW for Idioms (4 raw)")
md.append("- Strongest: Grammar Error Detection 20 clusters 7/7 papers, Preposition Article Fill Blank 25 clusters 7/7, Voice 10 clusters 6/7, Speech 10 clusters 6/7, Spelling 12 clusters 6/7, Comprehension 6 passages 6/7")
md.append("")
md.append("---")
md.append("# EXAMINER BLUEPRINT — ENGLISH (FROM RESEARCH)")
md.append("")
md.append("## Paper-wise Pattern [OBSERVED]")
md.append("| Paper | English Qs | Pattern |")
md.append("|-------|------------|---------|")
md.append("| 16 Nov 2024 | 20 Q51-70 | Q51-52 synonym, Q53-54 spelling, Q55 plural, Q56-57 error, Q58 idiom, Q59-60 one-word, Q61-62 preposition, Q63 fill blank, Q64-65 speech, Q66-67 voice, Q68-70 comprehension Birds & Mammals |")
md.append("| 22 Mar 2025 | 27 Q51-77 | Q51 speech, Q52 lying, Q53 error at night, Q54 edible one-word, Q55 deficient antonym, Q56 demand lot error, Q57 Govt Act rearrangement RQSP, Q58 had baked, Q59 unscrupulous antonym, Q60 Letter MTNL II,I,IV,III, Q61 grateful spelling, Q62 frugal vocab, Q63 active roads have been dug, Q64 noun Destroy Destruction, Q65 passive parents will send, Q66 grandeur synonym, Q67-70 Almond passage |")
md.append("| 25 Sep 2025 02-2026 | 20 Q51-70 | Q51 I love the dogs error, Q52 you will be broadcast error, Q53 failure demotivate, Q54 turbulence one-word, Q55 barracks, Q56 hedonist, Q57-59 voice passive, Q60-61 speech indirect, Q62-65 spelling Practice Quarentine Numerous Analytically Renewal, Q66-70 Mother Tongue passage additive subtractive |")
md.append("| 26 Sep 2025 | 20 Q51-70 | Q51 oppressive antonym humane, Q52 put cart before horse idiom, Q53 victory triumph, Q54 punctilious, Q55 Many determiner, Q56 can fix by tomorrow indirect could next day, Q57 had known conditional, Q58 DBCA arrange, Q59 boutique, Q60 since five years for, Q61 judicious sensible, Q62 is being played, Q63 water under bridge, Q64 has resolved, Q65 philosophy, Q66 desperate hopeful, Q67 discount on, Q68-70 RSV passage |")
md.append("| 27 Sep 2025 | 20 Q51-70 | Q51 consequency consequently, Q52 fill out for fill in for, Q53 girls is are, Q54 terribly performed performed terribly, Q55 had been intended, Q56 was loudly cheered, Q57 were, Q58 has risen, Q59 SRPQ Delegates, Q60 QRSP Russian invasion, Q61-64 Vivekananda standing ovation bureaucratic financial Parliament Vedanta Societies, Q65 distinct vague, Q66 animosity benevolence, Q67 Satisfy, Q68 optimist, Q69 curious, Q70 An honest |")
md.append("| 28 Sep 2025 | 20 Q51-70 | Q51 has being applying has been, Q52 absolutely best than better than, Q53 I reaches reach, Q54 for create to create, Q55 loathsome delightful, Q56 glorious modest, Q57 sacred profane, Q58 bite dust die, Q59 questionable, Q60 exagerate incorrect, Q61 spectecular incorrect, Q62 cautios incorrect, Q63 court of inquiry, Q64 walked, Q65 apologize to+base, Q66 ran, Q67 was playing, Q68 proposes and disposes universal truth no change, Q69 forbade, Q70 that week had spoiled her |")
md.append("| 30 Mar 2026 Official | 20 Q1-20 English | Q1 Defence noun, Q2 Each have has, Q3 wrote active, Q4 hyperbole, Q5 quiet, Q6 what he was doing there, Q7 library, Q8 goes->go subjunctive, Q9 an hour the work, Q10 RSPQ rain, Q11 She pronoun, Q12 harsh lenient, Q13 analysed, Q14 beyond, Q15 will have finished, Q16 gentle, Q17-20 Microplastics air soil drinking water travel long distances everywhere dirty unsafe most pass some stay |")
md.append("")
md.append("## Chapter Frequency [OBSERVED]")
md.append("| Chapter | Raw | Independent | ROI | Papers |")
md.append("|---|---:|---:|---|---|")
md.append("| Grammar Error Detection | 25 | 20 | 🔴 S | 7/7 |")
md.append("| Preposition Determiner Article Fill Blank | 30 | 25 | 🔴 S | 7/7 |")
md.append("| Voice Active/Passive | 12 | 10 | 🔴 S | 6/7 |")
md.append("| Speech Direct/Indirect | 12 | 10 | 🔴 S | 6/7 |")
md.append("| Spelling | 15 | 12 | 🔴 S | 6/7 |")
md.append("| Synonym/Antonym | 18 | 15 | 🟠 A | 6/7 |")
md.append("| One Word Substitution | 10 | 8 | 🟠 A | 5/7 |")
md.append("| Idioms | 6 | 4 | 🟡 B | 4/7 |")
md.append("| Comprehension Passage | 20 | 6 passages | 🔴 S | 6/7 |")
md.append("| Sentence Rearrangement + Dictionary | 12 | 10 | 🟠 A | 5/7 |")
md.append("")
md.append("## High-ROI Zones [STRONG INFERENCE]")
md.append("- 🔴 S MUST: Grammar Error (3-4Q per paper, 10-20 sec), Preposition Article (3-4Q), Voice (2Q), Speech (2Q), Spelling (1-2Q), Comprehension (3-4Q) = 13-16Q per paper = 65-80% of English section")
md.append("- 🟠 A HIGH: Synonym Antonym (1-2Q), One Word (1Q), Rearrangement (1-2Q) = 3-5Q")
md.append("- 🟡 B MEDIUM: Idioms (1Q per 2 papers)")
md.append("- ⚪ C LOW: Very hard vocab beyond PYQ list, rare one-word beyond list")
md.append("")
md.append("---")

# CHAPTER 1 - Grammar Error Detection - COMPLETE THEORY
md.append("# CHAPTER 1 — GRAMMAR ERROR DETECTION / INCORRECT PART — COMPLETE THEORY FOR 90+")
md.append("")
md.append("## 1. Why This Chapter Matters")
md.append("- Frequency: 25 raw, 20 independent mechanisms [OBSERVED], 7/7 papers")
md.append("- Approx contribution: 3-4Q per paper = 15-20% of English section")
md.append("- ROI: 🔴 TIER S — MUST MASTER")
md.append("- Confidence: HIGH")
md.append("- Priority: First 15 min me solve karna, fastest 10-20 sec per Q, 90%+ accuracy target for 90+ percentile")
md.append("")
md.append("## 2. COMPLETE THEORY — GRAMMAR ERROR DETECTION")
md.append("")
md.append("### 2.1 Subject-Verb Agreement — Complete")
md.append("**Rule:** Subject singular -> verb singular, Subject plural -> verb plural. Intervening words (of, along with, as well as, together with, etc) subject ko change nahi karte.")
md.append("")
md.append("**A. Basic:**")
md.append("- He has, They have, I have")
md.append("- Each/Every + singular noun + singular verb: Each student has (not have), Every boy has")
md.append("- Each of / Every one of / Either of / Neither of + plural noun + singular verb: Each of the students has (PYQ 30 Mar Q2), Neither of the boys has")
md.append("- Either...or / Neither...nor: Verb nearest subject ke according: Either he or they have, Either they or he has")
md.append("- Collective nouns: Team, Family, Government singular but can be plural if members individual: Team has (as unit), Team have (members individual) – PYQ me unit wala")
md.append("- Indefinite pronouns: Someone, Anyone, Everyone, Each, Every, One singular -> has")
md.append("- Along with, As well as, Together with, In addition to: First subject ke according verb: He along with his friends has (not have), The students along with teacher have? Actually first subject students plural have – but PYQ me He along with... has")
md.append("- Phrases between subject and verb: The happy and cheerful girls is -> are (subject girls plural) [PYQ 27 Sep Q53], The project was delayed (singular was)")
md.append("")
md.append("**B. PYQ Examples:**")
md.append("- Each of the students have reached -> has (Each singular) [PYQ 30 Mar Q2] [OBSERVED]")
md.append("- The happy and cheerful girls is always running -> are (girls plural) [PYQ 27 Sep Q53] [OBSERVED]")
md.append("- The project was delayed (correct, project singular was)")
md.append("")
md.append("**C. Trap:** Each have vs has – examiner plural noun dekh ke have trap deta hai, lekin Each singular has.")
md.append("")
md.append("### 2.2 Tense Consistency & Sequence")
md.append("**Rule:** Past me past, Present me present. Before + past perfect, After + past simple? Actually Before past perfect had baked before mother arrived (past perfect before past simple). By the time + future perfect will have finished.")
md.append("")
md.append("- **Past perfect before past:** I had baked cake before mother arrived [PYQ 22 Mar Q58] – Before past simple arrived, toh pehle wala action past perfect had baked.")
md.append("- **Tense consistency:** Researchers analyse (present) before they submitted (past) -> analysed (past) [PYQ 30 Mar Q13] – analyse present vs submitted past mismatch, dono past hona chahiye analysed before submitted.")
md.append("- **Future perfect by the time:** By the time conference starts she will be finishing -> will have finished [PYQ 30 Mar Q15] – By the time + present simple starts, future perfect will have finished (not continuous finishing).")
md.append("- **Future perfect will have + V3:** She will have participate -> participated [PYQ 16 Nov Q57] – will have + past participle, not base participate.")
md.append("- **Did + base:** did not went -> go [PYQ 25 Sep Q70] – did not ke baad base form go, not went.")
md.append("- **Has being vs has been:** Manish has being applying -> has been applying [PYQ 28 Sep Q51] – has been + V-ing present perfect continuous, being incorrect.")
md.append("- **Would have left if had known:** Third conditional If + had + V3, would have + V3 – I would have left if I had known you were not coming [PYQ 26 Sep Q57] – had known (past participle known not knew), had knew incorrect.")
md.append("- **Present perfect has risen last decade:** Population has risen very fast last decade [PYQ 27 Sep Q58] – last decade recent past present perfect has risen, not had been risen, not rising, not rises.")
md.append("- **Walked when child habitual past:** When I was child I walked to school every day [PYQ 28 Sep Q64] – habitual past simple walked, not have walked (present perfect) vs have been walking vs had walked.")
md.append("")
md.append("### 2.3 Since / For + Article + Comparative + Infinitive/Gerund")
md.append("- **Since point, For duration:** Since 2020, Since Monday, Since five years? Actually five years duration => For five years [PYQ 26 Sep Q60] – since five years incorrect, for five years correct.")
md.append("- **Absolutely + comparative/superlative:** Absolutely cannot have comparative/superlative? Absolutely best than -> better than (best cannot have than) or best without than [PYQ 28 Sep Q52] – The new smartphone is absolutely best than -> better than (comparative with than) or best (superlative without than) + absolutely cannot with comparative? Actually absolutely best is okay but best than not, better than correct.")
md.append("- **I/You/We + base not s/es:** I reaches -> reach [PYQ 28 Sep Q53] – I with s/es wrong, I reach correct.")
md.append("- **for + verb -> to + verb or for + V-ing:** for create enough jobs -> to create / for creating [PYQ 28 Sep Q54] – for create incorrect, to create infinitive correct.")
md.append("- **Subjunctive suggested that she go:** I suggested that she goes -> go [PYQ 30 Mar Q8] – suggested that + base form go (subjunctive), not goes.")
md.append("- **Generic plural no the:** I love the dogs (generic) -> I love dogs (no the) [PYQ 25 Sep Q51] – generic plural dogs no article the, specific the dogs (particular dogs) with the.")
md.append("- **Active vs Passive:** you will be broadcast the news -> will broadcast (active) [PYQ 25 Sep Q52] – you do action broadcast news, not be broadcast (passive means someone broadcasts you).")
md.append("- **Adverb position:** terribly performed -> performed terribly [PYQ 27 Sep Q54] – adverb manner after verb performed terribly, not before terribly performed (though both possible but PYQ says terribly performed error).")
md.append("- **Plural generic vs specific:** I love the dogs ; but I don't like the dog my friend owns – first the dogs generic error, second the dog specific correct.")
md.append("")
md.append("### 2.4 Phrasal Verbs + Conjunction")
md.append("- **fill in for vs fill out for:** Bindu asked Arya to fill out for her so that she could take care -> fill in for (someone) = replace, fill out = complete form – fill in for correct [PYQ 27 Sep Q52]")
md.append("- **No sooner inversion:** No sooner he was brought -> No sooner was he brought ... than [PYQ 16 Nov Q56] – No sooner at start inversion was he, not he was.")
md.append("- **Consequency vs consequently:** The project was delayed because of unforeseen issues consequency we had -> consequently (spelling + conjunctive adverb) [PYQ 27 Sep Q51]")
md.append("")
md.append("## 3. CORE RULES — GRAMMAR ERROR")
md.append("**RULE 1: Each/Every + singular verb**")
md.append("→ Explanation: Each/Every singular subject, verb singular has")
md.append("→ Correct: Each of the students has reached [PYQ 30 Mar Q2]")
md.append("→ Wrong: Each of the students have reached (have plural trap)")
md.append("→ Why wrong: Each singular has not have")
md.append("")
md.append("**RULE 2: No sooner inversion**")
md.append("→ Explanation: No sooner at beginning -> inversion was he + than")
md.append("→ Correct: No sooner was he brought to hospital than he began")
md.append("→ Wrong: No sooner he was brought [PYQ Q56]")
md.append("→ Why wrong: Inversion missing")
md.append("")
md.append("**RULE 3: will have + V3 future perfect**")
md.append("→ Explanation: will have + past participle")
md.append("→ Correct: She will have participated [PYQ Q57 corrected]")
md.append("→ Wrong: She will have participate (base)")
md.append("→ Why wrong: Future perfect needs V3")
md.append("")
md.append("**RULE 4: did not + base**")
md.append("→ Correct: did not go [PYQ Q70]")
md.append("→ Wrong: did not went")
md.append("→ Why: did not base form")
md.append("")
md.append("**RULE 5: Since point For duration**")
md.append("→ Correct: for five years [PYQ Q60]")
md.append("→ Wrong: since five years (five years duration not point)")
md.append("")
md.append("**RULE 6: Comparative best cannot have than**")
md.append("→ Correct: better than / best (without than) [PYQ Q52]")
md.append("→ Wrong: absolutely best than")
md.append("→ Why: best superlative no than, better comparative with than, absolutely cannot with comparative")
md.append("")
md.append("**RULE 7: I/You/We + base**")
md.append("→ Correct: I reach [PYQ Q53]")
md.append("→ Wrong: I reaches (s/es with I)")
md.append("")
md.append("**RULE 8: for + verb -> to + verb / for + V-ing**")
md.append("→ Correct: to create / for creating [PYQ Q54]")
md.append("→ Wrong: for create")
md.append("")
md.append("**RULE 9: has been not has being**")
md.append("→ Correct: has been applying [PYQ Q51]")
md.append("→ Wrong: has being applying")
md.append("")
md.append("**RULE 10: Plural subject are**")
md.append("→ Correct: girls are [PYQ Q53]")
md.append("→ Wrong: girls is")
md.append("")
md.append("**RULE 11: Adverb manner after verb**")
md.append("→ Correct: performed terribly [PYQ Q54]")
md.append("→ Wrong: terribly performed")
md.append("")
md.append("**RULE 12: Generic plural no the**")
md.append("→ Correct: I love dogs (generic) [PYQ Q51]")
md.append("→ Wrong: I love the dogs (generic with the)")
md.append("")
md.append("**RULE 13: Active vs Passive**")
md.append("→ Correct: you will broadcast news (you do) [PYQ Q52]")
md.append("→ Wrong: you will be broadcast news (passive means someone broadcasts you)")
md.append("")
md.append("**RULE 14: Tense consistency past past**")
md.append("→ Correct: analysed before submitted [PYQ Q13]")
md.append("→ Wrong: analyse (present) before submitted (past)")
md.append("")
md.append("**RULE 15: By the time future perfect**")
md.append("→ Correct: will have finished [PYQ Q15]")
md.append("→ Wrong: will be finishing (continuous)")
md.append("")
md.append("**RULE 16: fill in for vs fill out for**")
md.append("→ Correct: fill in for her (replace) [PYQ Q52]")
md.append("→ Wrong: fill out for (complete form)")
md.append("")
md.append("**RULE 17: Subjunctive suggested that she go**")
md.append("→ Correct: suggested that she go [PYQ Q8]")
md.append("→ Wrong: suggested that she goes")
md.append("")
md.append("## 4. EXAM SIGNALS — GRAMMAR ERROR")
md.append("- Each of / Every one of / Either of / Neither of + plural noun → immediately check singular verb has")
md.append("- No sooner at start → immediately check inversion was he + than")
md.append("- will have + verb → immediately check V3 participated not participate")
md.append("- did not + verb → immediately check base go not went")
md.append("- since/for + time → since point for duration")
md.append("- absolutely + best/better + than → check comparative best no than better than")
md.append("- I/You/We + verb with s/es → remove s")
md.append("- for + verb → to + verb / for + V-ing")
md.append("- has being → has been")
md.append("- Plural subject + is → are")
md.append("- Adverb before verb terribly performed → check position after verb")
md.append("- I love the dogs generic → no the")
md.append("- you will be broadcast news → active will broadcast")
md.append("- analyse before submitted → tense consistency past past")
md.append("- By the time + present simple → future perfect will have finished")
md.append("- fill out for her so that she could take care → fill in for")
md.append("- suggested that she goes → subjunctive go")
md.append("")
md.append("## 5. PYQ EVIDENCE — GRAMMAR ERROR")
md.append("- 16 Nov Q56 No sooner he was brought [OBSERVED] Pattern: No sooner inversion, Tested: Inversion, Correct: No sooner was he, Trap: he was")
md.append("- Q57 will have participate [OBSERVED] Pattern: Future perfect, Tested: V3, Correct: participated, Trap: base participate")
md.append("- 25 Sep Q70 did not went [OBSERVED] Pattern: did not + base, Tested: Base form, Correct: go, Trap: went")
md.append("- 26 Sep Q60 since five years [OBSERVED] Pattern: Since/For, Tested: For duration, Correct: for five years, Trap: since duration")
md.append("- 28 Sep Q52 absolutely best than [OBSERVED] Pattern: Comparative, Tested: better than / best without than, Correct: better than, Trap: best than")
md.append("- Q53 I reaches [OBSERVED] Pattern: I + base, Tested: Base, Correct: reach, Trap: reaches")
md.append("- Q54 for create [OBSERVED] Pattern: for + verb, Tested: to create / for creating, Correct: to create, Trap: for create")
md.append("- Q51 has being applying [OBSERVED] Pattern: has been, Tested: been not being, Correct: has been, Trap: being")
md.append("- 27 Sep Q53 girls is [OBSERVED] Pattern: Plural subject, Tested: are, Correct: are, Trap: is")
md.append("- Q54 terribly performed [OBSERVED] Pattern: Adverb position, Tested: performed terribly, Correct: performed terribly, Trap: terribly before")
md.append("- 25 Sep Q51 I love the dogs [OBSERVED] Pattern: Generic plural, Tested: No the, Correct: dogs, Trap: the dogs generic")
md.append("- Q52 you will be broadcast [OBSERVED] Pattern: Active vs Passive, Tested: Active will broadcast, Correct: will broadcast, Trap: be broadcast")
md.append("- 30 Mar Q13 analyse before submitted [OBSERVED] Pattern: Tense consistency, Tested: Past past, Correct: analysed, Trap: analyse present")
md.append("- Q15 will be finishing [OBSERVED] Pattern: By the time future perfect, Tested: will have finished, Correct: will have finished, Trap: will be finishing")
md.append("- Q2 Each have [OBSERVED] Pattern: Each singular, Tested: has, Correct: has, Trap: have")
md.append("- Q8 goes [OBSERVED] Pattern: Subjunctive suggested that she go, Tested: go base, Correct: go, Trap: goes")
md.append("- Q52 fill out for [OBSERVED] Pattern: Phrasal verb fill in for, Tested: fill in for, Correct: fill in for, Trap: fill out for")
md.append("")
md.append("## 6. QUESTION TYPES — GRAMMAR ERROR")
md.append("- Type A Direct rule: Each have, since five years, did not went – direct rule apply")
md.append("- Type B Hidden subject trap: The happy and cheerful girls is (adjective between subject and verb hides plural girls) – need subject identification girls plural")
md.append("- Type C Tense trap: analyse before submitted, will be finishing vs will have finished by the time – tense sequence")
md.append("- Type D Comparative trap: absolutely best than – best cannot have than")
md.append("- Type E Infinitive/Gerund trap: for create – for + V-ing or to + base")
md.append("- Type F Phrasal verb trap: fill out for vs fill in for – meaning difference")
md.append("- Type G Subjunctive trap: suggested that she goes -> go – special construction")
md.append("- Type H Generic vs Specific trap: I love the dogs generic vs the dog specific – article generic")
md.append("- Type I Active vs Passive trap: you will be broadcast vs will broadcast – voice")
md.append("- Type J Inversion trap: No sooner he was vs was he – inversion")
md.append("")
md.append("## 7. TRAP BANK — GRAMMAR ERROR")
md.append("| Trap | PYQ Evidence | Why Students Choose | Correct Approach | 10-sec Check |")
md.append("|---|---|---|---|---|")
md.append("| Each have vs has | 30 Mar Q2 Each have | Plural noun students have | Each singular has | Each/Every has 2 sec |")
md.append("| No sooner he was vs was he | 16 Nov Q56 | No inversion | No sooner was he inversion | No sooner was he |")
md.append("| will have participate vs participated | Q57 | Base vs participle | will have+V3 participated | will have+V3 |")
md.append("| did not went vs go | 25 Sep Q70 | Past after did | did not+base go | did not+base |")
md.append("| since five years vs for | 26 Sep Q60 | Since duration | for five years | Since point For duration |")
md.append("| absolutely best than vs better than | 28 Sep Q52 | Best with than | better than / best without than | best no than |")
md.append("| I reaches vs reach | Q53 | I with s/es | I reach base | I base |")
md.append("| for create vs to create | Q54 | for+base | to create / for creating | for+V-ing or to+base |")
md.append("| has being vs has been | Q51 | being vs been | has been | has been |")
md.append("| girls is vs are | 27 Sep Q53 | Singular verb plural subject | are | Plural are |")
md.append("| terribly performed vs performed terribly | Q54 | Adverb before | performed terribly after verb | Adverb after verb |")
md.append("| I love the dogs vs dogs generic | 25 Sep Q51 | The generic | Generic no the dogs | Generic no the |")
md.append("| will be broadcast vs will broadcast | Q52 | Passive vs active | will broadcast active | You do action active |")
md.append("| analyse vs analysed | 30 Mar Q13 | Present vs past | analysed past past | Past before past |")
md.append("| will be finishing vs will have finished | Q15 | Continuous vs perfect by the time | will have finished future perfect | By the time will have finished |")
md.append("| fill out for vs fill in for | 27 Sep Q52 | Complete form vs replace | fill in for replace | fill in for |")
md.append("| goes vs go subjunctive | 30 Mar Q8 | goes with she | suggested that she go base | Subjunctive go |")
md.append("")
md.append("## 8. 10-SECOND ATTACK — GRAMMAR ERROR")
md.append("1. Notice Each/Every/Each of -> singular verb has 2 sec eliminate have")
md.append("2. Notice No sooner at start -> inversion was he + than 2 sec eliminate he was")
md.append("3. Notice will have + verb -> V3 participated not participate 2 sec")
md.append("4. Notice did not + verb -> base go not went 2 sec")
md.append("5. Notice since/for + duration number years -> for 2 sec")
md.append("6. Notice absolutely + best/better + than -> better than (remove absolutely or best no than) 3 sec")
md.append("7. Notice I/You/We + s/es -> remove s reach not reaches 2 sec")
md.append("8. Notice for + verb -> to + verb or for + V-ing to create 2 sec")
md.append("9. Notice has being -> has been 2 sec")
md.append("10. Notice plural subject + is -> are 2 sec")
md.append("11. Notice adverb before verb terribly performed -> after verb performed terribly 3 sec")
md.append("12. Notice I love the dogs generic -> no the dogs 2 sec")
md.append("13. Notice you will be broadcast news -> active will broadcast 3 sec")
md.append("14. Notice analyse before submitted -> past past analysed 3 sec")
md.append("15. Notice By the time + present simple -> future perfect will have finished 3 sec")
md.append("16. Notice fill out for her so that she could take care -> fill in for 3 sec")
md.append("17. Notice suggested that she goes -> subjunctive go base 3 sec")
md.append("18. Eliminate No error if any above found, otherwise No error")
md.append("")
md.append("## 9. OPTION ELIMINATION — GRAMMAR ERROR")
md.append("- Eliminate have if Each/Every subject")
md.append("- Eliminate he was if No sooner at start (need was he)")
md.append("- Eliminate participate if will have (need participated)")
md.append("- Eliminate went if did not (need go)")
md.append("- Eliminate since if duration number years (need for)")
md.append("- Eliminate best than (best no than)")
md.append("- Eliminate reaches with I (need reach)")
md.append("- Eliminate for create (need to create)")
md.append("- Eliminate being if has being (need been)")
md.append("- Eliminate is if plural subject girls (need are)")
md.append("- Eliminate terribly performed (need performed terribly)")
md.append("- Eliminate the dogs generic (need dogs)")
md.append("- Eliminate be broadcast if you do action (need broadcast)")
md.append("- Eliminate analyse present if before submitted past (need analysed)")
md.append("- Eliminate will be finishing if By the time (need will have finished)")
md.append("")
md.append("## 10. PYQ-DERIVED EXAMPLES — GRAMMAR ERROR")
md.append("[PYQ-DERIVED PRACTICE] Each of the boys have submitted assignment -> has (Each singular)")
md.append("[PYQ-DERIVED] Since two hours I am waiting -> For two hours")
md.append("[PYQ-DERIVED] He did not goes to school -> go")
md.append("[PYQ-DERIVED] This is absolutely better than that -> better than (remove absolutely) or absolutely good")
md.append("[PYQ-DERIVED] I has completed work -> have")
md.append("[PYQ-DERIVED] She wants for eat ice cream -> to eat")
md.append("[PYQ-DERIVED] They has being playing since morning -> have been playing")
md.append("[PYQ-DERIVED] The children is playing -> are playing")
md.append("[PYQ-DERIVED] He quickly ran vs He ran quickly vs He terribly performed vs He performed terribly -> second correct for manner adverb after verb (though quickly both okay but terribly strongly after)")
md.append("[PYQ-DERIVED] I love the music vs I love music generic -> second no the generic")
md.append("[PYQ-DERIVED] The news will be broadcast vs They will broadcast news -> second active they do action")
md.append("[PYQ-DERIVED] He goes before he came -> went before came past past")
md.append("[PYQ-DERIVED] By the time he comes I will finish -> will have finished")
md.append("[PYQ-DERIVED] No sooner I had reached station than train left -> No sooner had I reached (inversion had I)")
md.append("[PYQ-DERIVED] I suggested that he goes -> go subjunctive")
md.append("")
md.append("## 11. COMMON CONFUSIONS — GRAMMAR ERROR")
md.append("| Confusion | Correct | Wrong | Trick |")
md.append("|---|---|---|---|")
md.append("| Each has vs have | Each has | Each have | Each singular |")
md.append("| Since vs For | Since 2020 (point) For five years (duration) | Since five years | Since point For duration |")
md.append("| did not went vs go | did not go | did not went | did+base |")
mod = []
mod.append("| Absolutely best than vs better than | better than / best (no than) | absolutely best than | best no than |")
mod.append("| I reaches vs reach | I reach | I reaches | I base |")
mod.append("| for create vs to create | to create / for creating | for create | for V-ing or to base |")
mod.append("| has being vs has been | has been applying | has being applying | has been |")
mod.append("| girls is vs are | girls are | girls is | Plural are |")
mod.append("| terribly performed vs performed terribly | performed terribly | terribly performed | Adverb after verb |")
mod.append("| I love the dogs vs dogs | I love dogs generic | I love the dogs generic | Generic no the |")
mod.append("| will be broadcast vs will broadcast | will broadcast active | will be broadcast (you do) | Active you do |")
mod.append("| analyse vs analysed | analysed before submitted | analyse before submitted | Past past |")
mod.append("| will be finishing vs will have finished | will have finished by the time | will be finishing | By the time future perfect |")
mod.append("| fill out for vs fill in for | fill in for replace | fill out for complete form | fill in for |")
mod.append("| goes vs go subjunctive | suggested that she go | suggested that she goes | Subjunctive base |")
mod.append("")
mod.append("## 12. MASTER CHECKLIST — GRAMMAR ERROR")
mod.append("□ Each/Every + singular has")
mod.append("□ No sooner inversion was he + than")
mod.append("□ will have + V3 participated")
mod.append("□ did not + base go")
mod.append("□ Since point For duration for five years")
mod.append("□ Comparative best no than better than absolutely cannot with comparative")
mod.append("□ I/You/We + base reach not reaches")
mod.append("□ for + verb -> to + verb / for + V-ing to create")
mod.append("□ has been not has being")
mod.append("□ Plural subject are not is girls are")
mod.append("□ Adverb manner after verb performed terribly")
mod.append("□ Generic plural no the I love dogs")
mod.append("□ Active vs passive will broadcast active")
mod.append("□ Tense consistency past past analysed before submitted")
mod.append("□ By the time future perfect will have finished")
mod.append("□ fill in for vs fill out for")
mod.append("□ Subjunctive suggested that she go base")
mod.append("")
# Continue with other chapters in same file - we need to append more

# For brevity, we will create second part file and then merge

with open('ENGLISH_DEEP_90PLUS_PART1.txt','w',encoding='utf-8') as f:
    f.write("\n".join(sections))
    f.write("\n".join(mod))

print("Part1 done 120+")
PY
